apiVersion: v1
kind: Secret
metadata:
  name: orderpage-backend-secret
  namespace: orderpage
  labels:
    app.kubernetes.io/name: orderpage-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: orderpage
type: Opaque
stringData:
  DB_USERNAME: change-me
  DB_PASSWORD: change-me
  JWT_SECRET_KEY: change-me-access-token-secret
  JWT_SECRET_KEY_RT: change-me-refresh-token-secret
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
