apiVersion: v1
kind: ServiceAccount
metadata:
  name: orderpage-backend
  namespace: orderpage
  labels:
    app.kubernetes.io/name: orderpage-backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: orderpage
