apiVersion: v1
kind: ConfigMap
metadata:
  name: orderpage-backend-config
  namespace: orderpage
data:
  DB_URL: jdbc:mariadb://orderpage-dev.cluster-xxxxxxxx.ap-northeast-2.rds.amazonaws.com:3306/ordersystem
  REDIS_HOST: orderpage-dev.xxxxxx.ng.0001.apn2.cache.amazonaws.com
  RABBITMQ_HOST: b-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.mq.ap-northeast-2.amazonaws.com
  RABBITMQ_PORT: "5671"
  RABBITMQ_SSL_ENABLED: "true"
  CORS_ALLOWED_ORIGINS: http://localhost:8081,http://localhost:8092,https://orderpage-fe-devops.vercel.app
